name: kaawa_mobile
description: A new Flutter project for connecting coffee farmers and buyers.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  sqflite: ^2.2.8+4
  path: ^1.8.2
  url_launcher: ^6.1.12
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  web_socket_channel: ^2.4.0
  intl: ^0.18.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  crypto: ^3.0.3
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatar.jpg
    - assets/images/fallback.jpg
    - assets/images/seeds.jpg
